previewsEnabled: true

services:
  - name: sso-api
    type: web
    region: oregon
    repo: https://github.com/yusufdupsc1/sso-platform
    branch: master
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sso_platform.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET
        generateValue: true
      - key: DEBUG
        value: "False"
